【反射】
（1）hasattr(obj, name_str)
	判断一个对象obj中，是否存在对应的name_str字符串的属性或方法
（2）getattr(obj, name_str)
	根据字符串取获取对象obj中，对应name_str的方法或属性的内存地址
（3）setattr(obj, 'y', z)
	设置属性或方法，其中对象obj，字符串'y'，即添加的属性或方法名， z为设置的内容
（4）delattr(obj, name_str)
	删除属性或方法

举例：	
def bulk(self):
    print("%s is yelling ... " % self.name)

class Dog(object):
    def __init__(self, name):
        self.name = name

    def eat(self, food):
        print("%s is eating %s..." % (self.name, food))

d = Dog("Lucky")
choice = input(">>: ").strip()

""" 判定属性或方法是否存在 """
if hasattr(d, choice):
    """ 调用属性
    attr = getattr(d, choice)
    print(attr)
    """
    """ 调用方法 """
    func = getattr(d, choice)
    func("dumpling")

    """ 删除属性
    delattr(d, choice)
    print(d.name)
    """
else:
    """ 添加方法
    setattr(d, choice, bulk)
	func = getattr(d, choice)
    func(d)
    """
    """ 添加属性 """
    setattr(d, choice, 22)
    print(getattr(d, choice))

""" 运作结果 """	
>>: talk
Lucky is yelling ... 


【异常处理】
（1）普通用法
try:
	code
""" 捕获一个错误 """	
except Error1 as e:
	print(e)
""" 捕获多个错误 """	
except (Error1, Error2) as e:
	print(e)
""" 捕获全部错误 """	
except Exception as e:
	print(e)
	
举例：
names = ['Tom', "Lucy"]
data = {"age": 22, "sex": "M"}

try:
    names[3]
    data['name']
    print("ddd")
except KeyError as e:
	print("Don't have the key", e )
except IndexError as e:
	print("list operation is wrong ", e)
except (KeyError, IndexError) as e:
    print("KeyError IndexError", e)
except Exception as e:
    print("error: ", e)
else:
    print("一切正常")
finally:
    print("不管是否有错，都执行")

（2）自定义异常
class MyExecption(Exception):
	def __init__(self, msg):
		self.message = msg

try:
	raise MyExecption("数据库连接不上")
except MyExecption as e:
	print(e)
	
（3）常见异常
AttributeError 试图访问一个对象没有的树形，比如foo.x，但是foo没有属性x
IOError 输入/输出异常；基本上是无法打开文件
ImportError 无法引入模块或包；基本上是路径问题或名称错误
IndentationError 语法错误（的子类） ；代码没有正确对齐
IndexError 下标索引超出序列边界，比如当x只有三个元素，却试图访问x[5]
KeyError 试图访问字典里不存在的键
KeyboardInterrupt Ctrl+C被按下
NameError 使用一个还未被赋予对象的变量
SyntaxError Python代码非法，代码不能编译
TypeError 传入对象类型与要求的不符合
UnboundLocalError 试图访问一个还未被设置的局部变量，基本上是由于另有一个同名的全局变量
ValueError 传入一个调用者不期望的值，即使值的类型是正确的

（4）不能捕获的场景
a）代码有语法错误
b）代码缩进存在问题